### ISSUE TITLE
Suspicious conversion

### ISSUE THREAD

**Issue by thelema** [yoriyuki/ucorelib#1]
```
let of_latin1 s = init (String.length s) (fun i -> UChar.of_char s.[i])
```

This code looks suspicious.  is it correct?  Is every Latin-1 character located at the corresponding Unicode codepoint?

**Comment by yoriyuki** [comment]
> Is every Latin-1 character located at the corresponding Unicode codepoint?

Yes, see for example, http://en.wikipedia.org/wiki/ISO/IEC_8859-1.
