### ISSUE TITLE
oasis setup

### ISSUE THREAD

**Issue by ygrek** [yoriyuki/ucorelib#2]
Why not commit oasis generated files?

**Comment by yoriyuki** [comment]
Um... usually I do not commit machine generated files to keep the patch "clean".  But thinking of all difficulties which installation of oasis have, I understand your need.  Any idea?

**Comment by ygrek** [comment]
A matter of taste I guess. I prefer to keep generated files in git so that users have less problems when building, another common approach is to put generated files only into release tarball but not in vcs.

**Comment by yoriyuki** [comment]
I will include setup.ml in the release tarball.  Thank you for commenting.

**Comment by ygrek** [comment]
(I would just like to note that not having setup.ml in git prevents it from being automatically built by build service, though one day I will probably install oasis on all build slaves)

**Comment by yoriyuki** [comment]
OK. I uploaded setup.ml and other files which look like required to build.   Could you try an automatic build?

**Comment by ygrek** [comment]
Missing : _tags (breaks build of test), Makefile (convenient).
BTW you can simplify .gitignore, as ocamlbuild doesn't pollute source dir, the following is enough imho :
*~
/_build
/setup.data
/setup.log
*.byte
*.native
*.docdir
/test/#UTF-8-test.txt#
/test/.#UTF-8-test.txt

**Comment by yoriyuki** [comment]
I've commited Makefile, _tags and META.  

Concerning .gitignore, I know it is not optimal for git.  But magit, which I use, apprently did not understand the simplified .gitignore.

**Comment by ygrek** [comment]
Now it is ok. Here is a patch for failing test - http://paste.in.ua/2564/
