### ISSUE TITLE
Add a tag for the latest stable version

### ISSUE THREAD

**Issue by samoht** [yoriyuki/ucorelib#4]
`ulib` is packaged with opam, but it is using the github master version. Would it be possible to add a tag to your tree to make a stable archive available on github's website ? (when you've done this, I can also change the library name in opam to `ucorelib`).

**Comment by yoriyuki** [comment]
The official answer is that there is no stable version yet, so use whatever branch at your own risk.  But I usually keep the master branch able to compile and pass the test.  So if you really want to package ucorelib, the master branch would be a good choice.

**Comment by samoht** [comment]
Well, `git tag 0.0.1` would be sufficient for me ...

**Comment by yoriyuki** [comment]
I think I made 0.0.1 branch.  Please test it.

**Comment by samoht** [comment]
Thank you very much! I've updated ucorelib to OPAM there: https://github.com/OCamlPro/opam-repository/commit/bdea2cca987705ca8c4de1c940bd3b7a8eb90192

now `opam install ucorelib` works fine!

Thanks again.
