### ISSUE TITLE
safe-string problem of OCaml 4.06

### ISSUE THREAD

**Issue by nekketsuuu** [yoriyuki/ucorelib#9]
After OCaml 4.06.0, the safe-string option is set at default (see GPR#1252 of https://ocaml.org/releases/4.06.html ). This change breaks the compilation of ucorelib under 4.06.0.

* First, update the version of OASIS, and then re-run `oasis setup`. The old `setup.ml` of OASIS can't be run under OCaml 4.06.0 due to the safe-string problem.
* Second, remove `String.set` and `String.copy`, which are deprecated (see https://caml.inria.fr/pub/docs/manual-ocaml/libref/String.html ). I grasped the code, and I noticed it is even used for `BaseString` module. So I don't touch it, and send an issue now.

**Comment by yoriyuki** [comment]
Camomile is upgraded for 4.06.  Use Camomile.  I won't develop ucorelib anymore.

**Comment by nekketsuuu** [comment]
OK, Thanks.
